### ISSUE TITLE
Set up TriBITS testing using GitHub Actions

### ISSUE THREAD

**Issue by bartlettroscoe** [TriBITSPub/TriBITS#363]
CC: @keita, @fnrizzi, @marcinwrobel1986, @MikolajZuzek 

With a lot of work on TriBITS going on and coming up (i.e. #63, #299, etc.) we need solid testing for TriBITS.  I have solid testing of TriBITS on local machines set up using the checkin-test.py script (see checkin-test-crf450.sh and those it calls) but we really need to have this for PR testing as well.  In the past, I did that with Travis CI.  But for reasons that I can't go into here, Travis CI is not a viable option going forward.

The obvious choice for this would seem to be to use GitHub Actions (GHA) for this.  But I don't know anything about GHA so this will be a learning curve.

For dependencies I need:

* CMake 3.17
* C++, C, and Fortran compilers
* Python 2.7

Other dependencies that would be nice to have:

* CMake current release (current CMake 3.19 but soon to be 3.20)
* Python 3.x
* Ninja 1.10+

And this would post to CDash at:

* https://testing.sandia.gov/cdash/viewSubProjects.php?project=TriBITS

At a minimum, there needs to be a build with:

* CMake 3.17 + Python 2.7 (or 3.x)

Other builds that would be nice to have include:

* CMake current + Python 3.x (or 2.7 if base build is using 3.x)
* CMake 3.17 + Ninja 1.10
* CMake 3.17 + Ninja 1.10 (no Fortran)

## Tasks:

* [x] Scope out new GitHub Actions driver (see PRs #366 and #389)
* [x] Create new branch '363-github-actions-tests' based off '377-provide-feedback-on-TriBITS-package-dependencies-data-structures-CI', rebase, clean up commits and create new PR .
* [x] Add install of docutils to github actions job and enable build_docs test.
* [x] Create file `tribits_cmake-3.21.0_makefiles_python-3.8_g++-9_tweaks.cmake` disables for cmake-3.21.0 GHA build to disable tests that fail with CMake 3.20.
* [x] Add new triggers `workflow_dispatch` and `schedule`.
* [x] Determine what branch the GitHub Action jobs was invoked on and send jobs to CDash to different CDash groups based on the event trigger: PRs and manual triggers to 'Experimental', pushes to 'master' to 'Continuous', cron jobs to 'Nightly' (see GITHUB_EVENT_NAME).
* [x] Set up TriBITS CDash site to send out emails if there are any failures reported to 'Continuous' or 'Nightly' dashboard'.
* [x] Merge new PR branch.
* [x] Create a side branch '363-github-actions-tests-show-ctest-3.21-defects' and create a PR that demonstrates the failures with CMake 3.21 that don't occur with CMake 3.17, post SNL Kitware issue ... See PR #394 and [SNL Kitware #184](https://gitlab.kitware.com/snl/project-1/-/issues/184).
* [x] Do a push to 'master' and verify that the builds are fired off and submit to the 'Continuous' CDash group.
* [x] Verify that the `workflow_dispatch` trigger works and submits to the `Experimental` CDash group.
* [x] Verify that the `schedule` trigger works and submits to the 'Nightly' CDash group.
* [x] Add pull request number to the build names and send results to CDash "Pull Request" Group for PR builds.

**Comment by bartlettroscoe** [comment]
@keita, @fnrizzi, @marcinwrobel1986, @MikolajZuzek,

Any of you guys have GitHub Actions experience that you could use to help set up automated testing on GitHub for TriBITS to help drive the TriBITS refactoring work?

**Comment by fnrizzi** [comment]
@bartlettroscoe 
Hi Ross! I have some, but minimal (related to C++ and Python testing for this project https://github.com/Pressio). 
I just connected with @marcinwrobel1986 @MikolajZuzek: they said they know GA a bit too. We also have another person in our group that knows it too. I would say we know enough that we can help out getting started. 
Speaking of this, Keita mentioned that he would setup a meeting between all of us for mid April to talk about the trilinos work. What if we try to schedule that soon and use to talk about this too?

**Comment by bartlettroscoe** [comment]
>  I have some, but not extensive (most of my GA experience relates to C++ and Python testing for this project https://github.com/Pressio).

@fnrizzi, it turns out that TriBITS testing is basically C++ and Python testing.  If you can test C++ and Python where CMake is building the C++ code, that is all that is needed for building and running the native TriBITS test suite.  I could use some help getting a starting GHA workflow in place with a few different jobs as described [above](https://github.com/TriBITSPub/TriBITS/issues/363#issue-838923383).

I have learned some about GHA in the last month from working on the backend workflow for https://bssw.io and the [bssw.io](https://github.com/betterscientificsoftware/bssw.io) GitHub project.

> Speaking of this, Keita mentioned that he would setup a meeting between all of us for mid April to talk about the trilinos work. What if we try to schedule that soon and use to talk about this too and how this fits the current work agreement we have?

Yes, let's coordinate this offline.

**Comment by fnrizzi** [comment]
@bartlettroscoe if you want, over the next few days I can try to setup a minimal GA workflow file that builds and runs the TriBITS tests to get started with. It would be minimal, but at least something to start from. It should be relatively easy to do since you said testing works like testing in C++. Would that be useful for you? And we can coordinate offline with Keita how to move forward.

**Comment by bartlettroscoe** [comment]
>  if you want, over the next few days I can try to setup a minimal GA workflow file that builds and runs the TriBITS tests to get started with

@fnrizzi, that would be great!  If the env has C, C++, Fortran, MPI, CMake 3.17, and Python 2.7+, the it should be as easy as:

```
$ mkdir <build-dir>
$ cd <build-dir>

$ cmake \
  -D TPL_ENABLE_MPI=ON \
  -D CMAKE_C_COMPILER=gcc \
  -D TriBITS_ENABLE_Fortran=ON \
  -D TriBITS_ENABLE_TESTS=ON \
  <tribits-base>

$ make

$ ctest -j16
``` 

If you can get that to configure, build, and run the tests, then I can take it from there and get this to submit to CDash and put in a nice link.

I guess you need to develop and test this GA workflow file in your fork of TriBITS (on the 'master' branch)?  That seems the only way to test and experiment with GA workflows before going into production.

**Comment by fnrizzi** [comment]
@bartlettroscoe ok, will try to have this ready by Monday or so, and will ping you then!

**Comment by fnrizzi** [comment]
@bartlettroscoe I have it running: https://github.com/fnrizzi/TriBITS/actions/runs/756848014

Some tests fail though: 
https://github.com/fnrizzi/TriBITS/runs/2365734531?check_suite_focus=true

I can change the action to run `ctest -V` to see the full log if you want.

**Comment by bartlettroscoe** [comment]
> Here is a draft of the yaml fle

@fnrizzi, very nice!  I will take this and and see if can't match the cases listed [above](https://github.com/TriBITSPub/TriBITS/issues/363#issue-838923383).  (I think there is 4 build cases to start out with.)

> I can change the action to run ctest -V to see the full log if you want (which you can also download btw)

I will set it up to post to CDash so we will be able to see the details very well there (and then I can fix any test failures).

I have a few questions ...

It would be nice to have a single job first run for the configuration:

* CMake 3.17 + Python 2.7 (or 3.x)

and if that passes, then run a set of other configurations like:

* CMake current (3.20) + Python 3.x (or 2.7 if base build is using 3.x)
* CMake 3.17 + Ninja 1.10
* CMake 3.17 + Ninja 1.10 (no Fortran)

That would reduce a lot of wasted computer cycles in case that single build did not work.

Does GitHub Actions support that?

I see this is running with `make -j4` and `ctest -j4`.  Doe the VMs running the GitHub action jobs have 4 cores?

**Comment by fnrizzi** [comment]
> @fnrizzi, very nice! I will take this and and see if can't match the cases listed [above](https://github.com/TriBITSPub/TriBITS/issues/363#issue-838923383). (I think there is 4 build cases to start out with.)

Do you want me to open a pull request or you just grab the yaml file? 

> It would be nice to have a single job first run for the configuration:
> * CMake 3.17 + Python 2.7 (or 3.x)
> and if that passes, then run a set of other configurations like:
> That would reduce a lot of wasted computer cycles in case that single build did not work.

I think it is possible, but not sure exactly how to do it. 
But also note that this is kind of what happens already because if one of the target config lines under the matrix does not work, are the other jobs are terminated 

> I see this is running with `make -j4` and `ctest -j4`. Doe the VMs running the GitHub action jobs have 4 cores?

Not sure! I actually read once that it is a reasonable assumption, and has always worked fine for me, but I can dig more to see if that really works or if there is a way to automate detecting the parallelism level (I think that is possible to do in Azure for instance)

**Comment by bartlettroscoe** [comment]
> Do you want me to open a pull request or you just grab the yaml file?

@fnrizzi, can you go ahead and clean up your git commits and post a PR?  That way you will get credit for this in git.

**Comment by fnrizzi** [comment]
@bartlettroscoe thanks! 
Here it is: https://github.com/TriBITSPub/TriBITS/pull/366

**Comment by bartlettroscoe** [comment]
@marcinwrobel1986, FYI, I merged #393 and things are looking good:

* https://testing.sandia.gov/cdash/index.php?project=TriBITS&date=2021-07-20

I still need to create an issue for the CMake 3.21 issues from PR #394 and verify that the different triggers work correctly.

**Comment by bartlettroscoe** [comment]
FYI: Looks like after the merge of PR #393, the 'push' trigger to 'master' kicked in and fired off the GHA builds [here](https://github.com/TriBITSPub/TriBITS/actions/runs/1050969559) and it correctly submitted the builds to the 'Continuous' group on CDash here:

* https://testing.sandia.gov/cdash/index.php?project=TriBITS&date=2021-07-20&filtercount=1&showfilters=1&field1=groupname&compare1=61&value1=Continuous

**Comment by bartlettroscoe** [comment]
FYI: The "Run workflow" button shows up a shown in the below screenshot:

![image](https://user-images.githubusercontent.com/1959736/126419317-f48c5f18-31ea-4eaf-aa73-5b2ac27be2f6.png)

and I fired it off to produce [this GHA run](https://github.com/TriBITSPub/TriBITS/actions/runs/1050998870) and it is shown on CDash [here](https://testing.sandia.gov/cdash/index.php?project=TriBITS&date=2021-07-20&filtercount=2&showfilters=1&filtercombine=and&field1=buildstarttime&compare1=83&value1=2021-07-21T02%3A07%3A50%20UTC&field2=buildstarttime&compare2=84&value2=2021-07-21T02%3A08%3A14%20UTC).

**Comment by bartlettroscoe** [comment]
Hum, the cron entry:

https://github.com/TriBITSPub/TriBITS/blob/3937fda397e55effea75c2b6f6f44c982845dd2b/.github/workflows/tribits_testing.yml#L8

did not run at midnight last night.  There is no GHA job shown [here](https://github.com/TriBITSPub/TriBITS/actions) and therefore nothing shown on CDash [here](https://testing.sandia.gov/cdash/index.php?project=TriBITS&date=2021-07-21).

I will need to dig into that to see why that is happening.

NOTE: The reason it is important to run a nightly build every day, even when no push is being done it is to ensure that the testing infrastructure does not change and get broken when there is inactivity for a while.  For example, if something in the container changes that breaks one of the builds but you don't post a PR or push to 'master' for a while, then it is a bad surprise when you do and the builds are broken.  By doing a nightly build, you will see within 24 hours when a change in the testing infrastructure breaks the builds (by getting emails both from GitHub and from CDash) and you can take action.

**Comment by marcinwrobel1986** [comment]
Hello @bartlettroscoe I took a look at that and basically seems to be correct. The time is UTC. There is also no notice it can not work with others like `push` or `PR`. Strange. Maybe give it one more day.

**Comment by bartlettroscoe** [comment]
> Hello @bartlettroscoe I took a look at that and basically seems to be correct. The time is UTC.

@marcinwrobel1986, right UTC!  Of course it has to be UTC.  So midnight UTC is 8 PM EDT.  I will change this temporarily to 16:00 UTC (12 noon EDT) to make sure this fires off.

**Comment by bartlettroscoe** [comment]
> There is also no notice it can not work with others like `push` or `PR`.

@marcinwrobel1986, I don't see anything about `schedule` events not working with `push` or `pull_request` events at at:

* https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events

Where do you see that?

Anyway, I realized I pushed to the branch instead of 'master' so I just pushed again to fire off at 16:10 UTC (so in 5 min).

**Comment by marcinwrobel1986** [comment]
I wrote there is `no` notice :). Firstly I thought, there might be a conflict, but I have not found anything.

**Comment by bartlettroscoe** [comment]
FYI: The cron job that I set for 16:10 UTC (12:10 EDT) finally fired off at 12:39 PM EDT as shown [here](https://github.com/TriBITSPub/TriBITS/actions/runs/1053291080) and submitted to the 'Nightly' CDash group as shown [here](https://testing.sandia.gov/cdash/index.php?project=TriBITS&date=2021-07-21&filtercount=1&showfilters=1&field1=groupname&compare1=61&value1=Nightly).  I just pushed the commit 7fd89f022bf4b4c0ede353991bf8c819ebeed301 to move this back to 04:10 UTC (or 10 minutes after midnight EDT). 

So I will watch for the nightly build to show up tomorrow morning and we should be good on that.

**Comment by bartlettroscoe** [comment]
FYI: To make it easier to pick out manual builds on CDash, I added commit 43480b75342606cf8027071e78905327661da171 which now allows you to set a suffix for the build names on CDash and I used that to generate builds:

*  https://testing.sandia.gov/cdash/index.php?project=TriBITS&date=2021-07-21&filtercount=1&showfilters=1&field1=buildname&compare1=66&value1=_test_1

showing:

| Site | Build Name | Conf Error| Conf Warn | Conf Test Time | Build Error| Build Warn | Build Test Time | Test Not Run | Test Fail | Test Pass | Test Time | Start Test Time
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
ubuntu-latest | tribits_cmake-3.17.5_makefiles_python-3.8_g++-11_nofortran_test_1 | 0 | 0 | 3s | 0 | 0 | 0s | 0 | 0 | 335 | 2m 8s | 5 hours ago
ubuntu-latest | tribits_cmake-3.17.5_makefiles_python-2.7_g++-8_test_1 | 0 | 0 | 5s | 0 | 0 | 0s | 0 | 0 | 374 | 5m 1s | 5 hours ago
ubuntu-latest | tribits_cmake-3.17.5_makefiles_python-3.8_g++-10_test_1 | 0 | 0 | 11s | 0 | 0 | 1s | 0 | 0 | 374 | 5m 11s | 5 hours ago
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9_test_1 | 0 | 0 | 8s | 0 | 0 | 0s | 0 | 0 | 364 | 4m 27s | 5 hours ago

Now all that is left to close this issue is the nightly builds firing off after 10 minutes after midnight EDT (4 AM UTC).

**Comment by bartlettroscoe** [comment]
NOTE: Another thing that would improve this and make it easier to find results on CDash is to include the PR number in the build name.  You can do that as described in https://github.com/actions/checkout/issues/58.  Apparently you get it from:

```
pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
```

I will have to keep that in mind.  For now, there are not a lot of PRs being sent for TriBITS so this is not a big deal.  Also, working #154 would help some as well.

**Comment by bartlettroscoe** [comment]
NOTE: The cron job specified at:

https://github.com/TriBITSPub/TriBITS/blob/7fd89f022bf4b4c0ede353991bf8c819ebeed301/.github/workflows/tribits_testing.yml#L5

did fire off after 12:10 AM EDT last night at around 12:38 AM EDT as shown [here](https://github.com/TriBITSPub/TriBITS/actions/runs/1054930482) with results shown on the 'Nighty'  CDash group as shown here:

* https://testing.sandia.gov/cdash/index.php?project=TriBITS&filtercount=1&showfilters=1&field1=groupname&compare1=61&value1=Nightly

In addition, I just created PR #386 that prepends `pr-<id>_` for the PR ID for builds for PRs being tested and it sends results to a new "Pull Request" CDash Group.  That makes it much easier to pick out results on CDash.  The last thing to improve this is to put in a better link from the GitHub Actions output to the results on CDash as described in #154 (using info in the TAG file).  Since I know how to do that and since I am on a roll, I think I will just implement the better URL (not the TriBITS Dashboard Driver stuff).

**Comment by bartlettroscoe** [comment]
With #154 scoped correctly and added to the board and everything else above completed, I am going to call this done.

@fnrizzi and @marcinwrobel1986, thanks for all of your help on this.  This is really going to help with getting refactorings and updates to TriBITS done in the future as we can now all have a solid basis of comparison for testing changes to TriBITS.

**Comment by marcinwrobel1986** [comment]
@bartlettroscoe Thanks Ross!

**Comment by bartlettroscoe** [comment]
FYI: I also realized I needed to update the TriBITS GitHub wiki that was still mentioning Travis CI.  See [here](https://github.com/TriBITSPub/TriBITS/wiki) and [here](https://github.com/TriBITSPub/TriBITS/wiki/TriBITS-CDash-Dashboard).
