### ISSUE TITLE
Address issues from TriBITS snapshot into Trilinos from PR trilinos/Trilinos#9894 (#299)

### ISSUE THREAD

**Issue by bartlettroscoe** [TriBITSPub/TriBITS#433]
**Parent Issue:**
* #299

**Child Issues:**
* #443

## Description

This issue is to track TriBITS work to address the problems that were identified with the merge of the updated TriBITGS snapshot into Trilinos with the merge of Trilinos PR trilinos/Trilinos#9894 which lead the the revert PR trilinos/Trilinos#9977.  The fixes will be snapshotted to the branch in Trilinos PR trilinos/Trilinos#9978.  All of this is related to #299.

## Tasks

* [x] 1. Issues causing Albany configure failures from trilinos/Trilinos#9972 ... See PR #435
* [x] 2. Handling of general linker options in `TPL_<tplName>_LIBRARIES` like `-mkl` described in https://github.com/trilinos/Trilinos/pull/9978#issuecomment-982834778
* [x] 3. Handling of library names in `TPL_<tplName>_LIBRARIES` described in https://github.com/trilinos/Trilinos/pull/9978#issuecomment-982166363
* [x] 4. Bring back DEPRECATED non-namespace IMPORTED targets (see https://github.com/TriBITSPub/TriBITS/issues/299#issuecomment-1011558738).
* [x] 5. Reproducing and fixing issues with Nalu (see https://github.com/trilinos/Trilinos/pull/9978)
* [x] 6. Reproducing and determine how to fix issues with SPARC (see https://github.com/trilinos/Trilinos/pull/9978)
* [x] 7. Document change to `-isystem` for IMPORTED targets and workarounds (see #443)
* [x] 8. Update TriBITS snapshot in https://github.com/trilinos/Trilinos/pull/9978 and update Trilinos release notes and build reference documents (see #443)
* [ ] 9. Get Trilinos PR trilinos/Trilinos#9978 merged to Trilinos 'develop'

**Comment by bartlettroscoe** [comment]
CC: @marcinwrobel1986, @mperrinel

PR #435 should address the configure failures with Albany and Nalu reported in trilinos/Trilinos#9972 and trilinos/Trilinos#9973.

**Comment by bartlettroscoe** [comment]
I am having to create reference builds of several application codes with Trilinos so that I can compare with the updated TriBITS build system.  This is taking a lot of time so I am putting this back in progress.

**Comment by bartlettroscoe** [comment]
I have debugged the problem with Albany and the updated TriBITS build system with Trilinos that is in https://github.com/trilinos/Trilinos/pull/9978.  The issue is described in detail in https://github.com/TriBITSPub/TriBITS/issues/299#issuecomment-1011558738.  We need to decide to what level of backwards compatibility we are going to maintain (even incorrect usage of TriBITS?).

**Comment by bartlettroscoe** [comment]
Next, I am going to bring back deprecated non-namespaced IMPORTED targets as per https://github.com/TriBITSPub/TriBITS/issues/299#issuecomment-1012363825 before moving on the Nalu and SPARC.

**Comment by bartlettroscoe** [comment]
The issue with SPARC has exposed another serious break in backwards compatibility.   See https://github.com/TriBITSPub/TriBITS/issues/299#issuecomment-1027514592 and #443 (and let's not discuss it here).

**Comment by bartlettroscoe** [comment]
FYI: We have given SPARC its own gtest implementation to resolve the build issues on the 'van1-tx2' system as implemented in internal MR [sparc/sparc-ear99!882](https://cee-gitlab.sandia.gov/sparc/sparc-ear99/-/merge_requests/882).  Once they merge that, MR to SPARC 'master', this SPARC issue will no longer be an impediment for this TriBITS work.  But we still need to address (at least with documentation) the `-isystem` problem in #443.

**Comment by bartlettroscoe** [comment]
With the merge of internal MR [sparc/sparc-ear99!890](https://cee-gitlab.sandia.gov/sparc/sparc-ear99/-/merge_requests/890), SPARC now has its own internal build of gtest that will be used instead of any other gtest installed in Trilinos or on the system (because the include dirs for the internally build gtest are included with -I and come before all other include dirs).

**Comment by bartlettroscoe** [comment]
FYI: I verified that the internal build of googletest (gtest) with SPARC does not appear to have broken any of their nighty builds.  See [internal issue tribitsrefactoring#3](https://cee-gitlab.sandia.gov/rabartl/tribitsrefactoring/-/issues/3#note_2184795).

Now, I can't do this amount of work for every application code that breaks a build due to this upgrade of TriBITS.  But at least now with this SPARC case resolved, I can point to that to prove that the include directory issues can be resolved in a case like gtest by simply building the package's own gtest and putting its include dirs first with -I.

**Comment by bartlettroscoe** [comment]
The Trilinos PR #9978 is now updated to resolve everything listed in "Tasks" [above](https://github.com/TriBITSPub/TriBITS/issues/433#issue-1076074013).  Now we just need to merge that PR to Trilinos 'develop'.

As I noted in https://github.com/trilinos/Trilinos/pull/9978#issuecomment-1060942454, Trilinos 'develop' is now **6 months behind** TriBITS 'master'.

**Comment by bartlettroscoe** [comment]
The merge of #10614 a week ago with no related issues reported (but a new set of issues reported) seems to suggest we can close this issue.
